account_app/urls.py
from django.urls import path

from . import views

app_name = 'account_app'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    # path('products' , views.ProductListView.as_view(), name='products'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('addaddress/', views.AddAddressView.as_view(), name='addAddress'),
    path('editaddress/<int:pk>/', views.EditAddressView.as_view(), name='editAddress'),
    path('deleteaddress/<int:pk>/', views.DeleteAddressView.as_view(), name='deleteAddress'),

    # ////////////////////////////////////////////////////

    path('upload_profile_picture/', views.upload_profile_picture, name='upload_profile_picture'),
    path('delete_profile_picture/', views.delete_profile_picture, name='delete_profile_picture'),

    # //////////////////////////////////////////////////////
    path('contact/', views.ContactUsView.as_view(), name='contact_form_submit'),
]

coffee/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import path , include
from coffee import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home_app.urls")),
    path('account/',include("account_app.urls")),
    path('',include("product_app.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_app/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'home_app'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('faq/', views.FAQView.as_view(), name='FAQ'),
    path('guarantee/', views.GuaranteeView.as_view(), name='guarantee'),

]

product_app/urls.py
# from django.urls import path
from . import views
#
# urlpatterns = [
#     path('products_list', views.ProductListView.as_view(), name='product_list'),
#     path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
#     path('reply/<int:review_id>/', views.add_reply, name='add_reply'),
# #     ////////////////////////////////////
#     path('order/add' , views.OrderCreationView.as_view(), name='order_create'),
#
# ]

from django.urls import path
from . import views

app_name = 'product_app'

urlpatterns = [
    path('reply/<int:review_id>/', views.add_reply, name='add_reply'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products', views.ProductListView.as_view(), name='product_list'),

    # ////////////////////////////////////////////////////////////////////////
    path('addproduct/<int:pk>', views.ProductAddOrderView.as_view(), name='product_add'),
    path('ordernotregistered/', views.OrderNotRegisteredView.as_view(), name='order_detail'),
    path('orderdetail/<int:pk>' , views.OrderDetailsView.as_view(), name='order_id_search'),
    path('orderconfirm' , views.ConfirmOrderView.as_view(), name='order_confirm'),
    path('apply_discount/', views.ApplyDiscountView.as_view(), name='apply_discount'),
    path('remove_discount/', views.RemoveDiscountView.as_view(), name='remove_discount'),
    path('update_order_item/', views.UpdateOrderItemView.as_view(), name='update_order_item'),
    path('delete_order_item/', views.DeleteOrderItemView.as_view(), name='delete_order_item'),

    path('select_address/<int:address_id>/', views.select_address, name='select_address'),

]

templates/includes/home_page/best-selling.html
{% load static %}
{% load humanize %}
<!-- best-selling  -->
<section class="best-selling mb-8 md:mb-20">
    <div class="container">
        <div class="flex justify-between items-end mb-5 md:mb-12 ">
            <!-- best-selling list  -->
            <!-- best-selling header  -->
            <div>
                <h3 class="section-title">محصولات پر فروش</h3>
                <span class="section-subtitle">پیشنهاد قهوه خور ها ...</span>
            </div>
            <!-- swiper  -->
            <div class="flex gap-x-3 md:gap-x-[18px]">
                <div class="swiper-button-next-custom ">
                    <svg class=" w-5 h-5 md:w-[20px] md:h-[20px] rotate-180">
                        <use href="#chevron-left-mini"></use>
                    </svg>
                </div>
                <div class="swiper-button-prev-custom">
                    <svg class="w-5 h-5 md:w-[20px] md:h-[20px]">
                        <use href="#chevron-left-mini"></use>
                    </svg>
                </div>
            </div>
            <!-- Slider main container -->

        </div>
        <div class="swiper">
            <!-- Additional required wrapper -->
            <div
                    class="swiper-wrapper child:bg-white child:dark:bg-zinc-700 shadow-normal child:rounded-2xl child:p-2 child:md:p-5">
                <!-- Slides -->
                    
                {% for product in best_selling_products %}
                    <div class="swiper-slide">
                        <!-- Images and discount -->
                        <div class="relative mb-2 md:mb-5">
                            {% if product.images.exists %}
                                <img src="{{ product.images.first.image.url }}" class="md:w-auto mx-auto" loading="lazy"
                                     alt="{{ product.images.first.alt_text }}">
                            {% else %}
                                <img src="{% static 'img/products/productDefault.png' %}" class="md:w-auto mx-auto"
                                     loading="lazy"
                                     alt="product img not loaded">
                            {% endif %}
                            {% if product.discount_percentage %}
                                {% if product.status == "in_stock" %}

                                    <span class="absolute block top-1 right-1 bg-orange-300 h-5 md:h-[30px] rounded-full px-2.5 md:px-3 py-1 font-DanaDemiBold text-xs md:text-base text-white dark:text-zinc-700">
                                {{ product.discount_percentage }}%
                            </span>
                                {% endif %}
                            {% endif %}
                        </div>
                        <!-- Product title -->
                        <a href="{% url 'product_app:product_detail' product.id %}"
                           class="text-sm md:text-xl line-clamp-2 text-zinc-700 dark:text-white mt-2 md:mt-5 mb-1.5 md:mb-2.5 h-10 md:h-14">
                            {{ product.name }}
                        </a>
                        <!-- Price -->
                        <div class="flex gap-x-2 md:gap-2.5 pb-2.5 md:pb-4 items-center">
                            {% if product.status == 'in_stock' %}
                                {% if product.discount_percentage %}
                                    <div class="flex items-center text-gray-400 line-through decoration-red-400">
                                        <span class="text-sm md:text-xl">{{ product.price|intcomma }}</span>
                                        <!-- استفاده از فیلتر intcomma -->
                                        <span class="hidden md:inline-block text-sm tracking-tighter">تومان</span>
                                    </div>
                                    <div class="flex items-center text-teal-600 dark:text-emerald-500">
                                    <span class="text-base md:text-xl font-DanaDemiBold">
                                        {{ product.get_final_price|intcomma }}  <!-- استفاده از فیلتر intcomma -->
                                    </span>
                                        <span class="text-xs md:text-sm tracking-tighter">تومان</span>
                                    </div>

                                {% else %}
                                    <div class="flex items-center text-teal-600 dark:text-emerald-500">
                                    <span class="text-base md:text-xl font-DanaDemiBold">
                                        {{ product.price|intcomma }}  <!-- استفاده از فیلتر intcomma -->
                                    </span>
                                        <span class="text-xs md:text-sm tracking-tighter">تومان</span>
                                    </div>
                                {% endif %}
                            {% else %}
                                <div class="text-red-400 text-base md:text-xl">
                                    محصول موجود نیست
                                </div>
                            {% endif %}
                        </div>
                        <!-- Shopping and comparison SVG -->
                        <div class="flex justify-between items-center">
                            <a href="{% url 'product_app:product_detail' product.id %}" class="flex gap-px md:gap-1.5">
                                <svg class="w-7 h-7 p-1 md:w-9 md:h-9 md:p-2 rounded-full text-gray-400 bg-gray-100 stroke-[1.5px] dark:bg-zinc-800 hover:bg-teal-600 dark:hover:bg-emerald-500 hover:text-white cursor-pointer transition-all">
                                    <use href="#shopping-cart"></use>
                                </svg>

                            </a>
                            <!-- Rating -->
                            <div class="flex items-center">
                                <div class="flex items-center">
                                    <div class="flex flex-row-reverse">
                                        {% for i in "12345" %}
                                            {% if forloop.counter <= product.calculate_average_rating %}
                                                <svg class="w-4 h-4 md:w-6 md:h-6 text-yellow-400 border-solid">
                                                    <use href="#star"></use>
                                                </svg>
                                            {% else %}
                                                <svg class="w-4 h-4 md:w-6 md:h-6 text-gray-300 dark:text-gray-400">
                                                    <use href="#star"></use>
                                                </svg>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                    <div class="text-xs md:text-sm text-white ml-2 pr-2" style="padding-top: 6px">
                                        {{ product.calculate_average_rating|floatformat:1 }} / 5
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>


        </div>

    </div>
</section>

templates/includes/home_page/category-banner.html
{% load static %}        
<!-- category-banner  -->
        <section class="category-banner mt-8 mb-10 md:my-20">
            <div class="container ">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-5 text-white ">
                    <div 
                        class="category-banner__item1 gap-4 md:gap-5 pr-7 md:pr-12 flex flex-col justify-center h-[142px] md:h-[248px] rounded-2xl">
                        <span class="font-DanaDemiBold text-2xl/6 md:text-4xl/6 mb-4 md:mb-7">انواع قهوه</span>
                        <span class="md:font-DanaDemiBold md:text-xl/6">ترکیبی و تک خاستگاه</span>
                    </div>
                    <div
                        class="category-banner__item2 gap-4 md:gap-5 pr-7 md:pr-12 flex flex-col justify-center h-[142px] md:h-[248px] rounded-2xl">
                        <span class="font-DanaDemiBold text-2xl/6 md:text-4xl/6 mb-4 md:mb-7">پودر های فوری</span>
                        <span class="md:font-DanaDemiBold md:text-xl/6">نسکافه ، هات چاکلت ، ماسالا</span>
                    </div>
                </div>
            </div>
        </section>

templates/includes/home_page/coffee-club.html
{% load static %}
        <!-- caffe-club  -->
        <section class="coffe-club mb-8 md:mb-20">
            <div class="container">

                <!-- lg:gap-x-4 xl:gap-x-24 gap-y-9 -->
                <div
                    class="flex items-center flex-wrap lg:flex-nowrap lg:gap-x-4 xl:gap-x-24 gap-y-9 bg-gradient-to-t from-emerald-500 to-emerald-600 text-white py-8 lg:py-0 px-3 lg:px-5 xl:px-11 lg:h-36 rounded-2xl">

                    <div class="flex items-center gap-x-3 md:gap-x-4 xl:gap-x-6 md:shrink-0">
                        <!-- img coffe-club  -->

                        <img src="{% static 'img/club/diamond.png' %}" class="w-[87px] md:w-[100] xl:w-[110px]"
                             alt="coffe-club">
                        <div>
                            <h4 class=" font-MorabbaBold text-2xl md:text-5xl mb-2">کافی کلاب</h4>
                            <p class=" font-MorabbaLight text-lg md:text-2xl">میدونستی میتونی با امتیاز هات قهوه بگیری ؟
                            </p>
                        </div>
                    </div>

                    <div class="flex justify-between w-full">
                        <div class="flex gap-x-2 lg:gap-x-3 xl:gap-x-5">
                            <div
                                class="w-[72px] h-[72px] md:w-[98px] md:h-[98px] text-center text-emerald-600 bg-white py-1.5 md:pt-5 md:pb-1 rounded-2xl">
                                <svg class="w-10 h-10 md:w-12 md:h-12 mb-1 md:mb-1.5 mx-auto">
                                    <use href="#discovery"></use>
                                </svg>
                                <span class="text-xs md:text-sm">چرخ و بخت</span>
                            </div>
                            <div
                                class="w-[72px] h-[72px] md:w-[98px] md:h-[98px] text-center text-emerald-600 bg-white py-1.5 md:pt-5 md:pb-1 rounded-2xl">
                                <svg class="w-10 h-10 md:w-12 md:h-12 mb-1 md:mb-1.5 mx-auto">
                                    <use href="#activity"></use>
                                </svg>
                                <span class="text-xs md:text-sm">ماموریت ها</span>
                            </div>
                            <div
                                class="w-[72px] h-[72px] md:w-[98px] md:h-[98px] text-center text-emerald-600 bg-white py-1.5 md:pt-5 md:pb-1 rounded-2xl">
                                <svg class="w-10 h-10 md:w-12 md:h-12 mb-1 md:mb-1.5 mx-auto">
                                    <use href="#ticket-star"></use>
                                </svg>
                                <span class="text-xs md:text-sm">جایزه ها</span>
                            </div>
                        </div>
                        <div class="flex flex-col">
                            <span class="md:mb-1 font-DanaDemiBold text-2xl md:text-3xl">542</span>
                            <span class="text-xs md:text-sm">امتیـــــــاز شما</span>
                            <div>
                                <a href="#"
                                    class="flex items-center justify-center mt-1 md:mt-2 w-[90px] md:w-[110px] h-[26px] md:h-8 bg-gradient-to-r from-orange-200 to-orange-300 font-DanaMedium text-xs md:text-sm rounded-full mr-[-6px]">دریافت
                                    جایزه
                                    <svg class="w-5 h-5 md:w-6 md:h-6">
                                        <use href="#chevron-left-mini"></use>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>



                </div>

            </div>
        </section>

templates/includes/home_page/contact-us.html
{% load static %}
        <!-- contact-us  -->
        <section class="contact-us mb-16 md:mb-28">
            <div class="container">
                <div
                    class="flex flex-col lg:flex-row items-center lg:items-start gap-y-8 lg:gap-x-5 text-zinc-700 dark:text-white">
                    <img src="{% static 'img/contact.png' %}" class="flex-shrink-0 w-[296px] h-[305px]" alt="contact-us">
                    <div>
                        <div class="font-MorabbaMedium text-2xl md:text-5xl mb-0.5 md:mb-1.5">یکی از بهترین قهوه ها !
                        </div>
                        <div class="font-MorabbaLight text-lg md:text-3xl/[48px]">کیفیت قهوه را از ما بخواهید ...</div>
                        <div class="flex gap-x-2.5 my-5 md:my-6">
                            <span class="inline-block w-1 h-1 rounded-full bg-zinc-700 dark:bg-gray-400"></span>
                            <span class="inline-block w-1 h-1 rounded-full bg-zinc-700 dark:bg-gray-400"></span>
                            <span class="inline-block w-1 h-1 rounded-full bg-zinc-700 dark:bg-gray-400"></span>
                        </div>
                        <div class="font-DanaRegular text-lg md:text-2xl/8 md:mb-3.5">فضای گرم و دنج ما را احساس کنید،
                            جایی که همه
                            می توانند قهوه معطری پیدا کنند و دسرهای خوشمزه
                            ما را که کاملاً با قهوه داغ همراه شده است، امتحان کنند. فضای داخلی شیک و کارکنان خوش برخورد
                            ما روز شما را می سازد!</div>
                        <a href="{% url 'account_app:contact_form_submit' %}"
                            class="inline-flex items-center h-[50px] md:h-[60px] gap-x-2 px-6 mt-5 md:mt-6 border md:border-2 border-orange-300 justify-center text-base md:text-xl tracking-tightest text-orange-300 hover:bg-gray-200 hover:dark:bg-gray-700 rounded-full transition-all delay-75">

                            <svg class="w-5 h-5 md:w-8 md:h-8">
                                <use href="#phone"></use>
                            </svg>

                            <span>ثبت سفارش تلفنی</span>
                        </a>
                    </div>
                </div>
            </div>
        </section>

templates/includes/home_page/footer.html
{% load static %}

<!-- footer  -->
<footer class="relative bg-zinc-700 py-8 md:pb-11 pt-[62px]">
    <!-- curve  -->
    <svg
            class="rotate-180 absolute top-0 right-0 left-0 mx-auto hidden md:inline-block text-gray-100 dark:text-zinc-800 w-[100px] h-[22px]">
        <use href="#curve"></use>
    </svg>
    <!-- Arrow circle  -->
    <div
            class="absolute top-0 right-0 left-0 mx-auto -translate-y-2/4 hidden md:flex items-center justify-center w-[30px] h-[30px] border-2 border-orange-300 rounded-full">
        <svg class="w-5 h-5 text-zinc-700 dark:text-white rotate-180">
            <use href="#chevron-down"></use>
        </svg>
    </div>
    <div class="sm:w-[94%] lg:w-[90%] px-4 md:px-0 mx-auto text-gray-300">
        <div class="flex flex-wrap justify-between">
            <!-- details wabsite  -->
            <div>
                <div class="flex gap-x-5 mb-6 md:mb-4.5 text-gray-300">
                    <svg class="w-[57px] h-[54px]">
                        <use href="#logo"></use>
                    </svg>
                    <svg class="w-[138px] h-[54px]">
                        <use href="#logo-type"></use>
                    </svg>
                </div>
                <p class="max-w-[606px] lg:max-w-full xl:max-w-[606px] text-lg md:text-xl/[48px]">
                    {{ footer_info.description }}
                </p>
            </div>
            <!-- fast access  -->
            <div class="mt-10 md:mt-[26px]">
                <h4 class="font-DanaDemiBold text-2xl text-white mb-6 md:mb-7">درسترسی سریع</h4>
                <div class="grid grid-cols-2 gap-y-2.5 gap-x-10 md:gap-y-5 md:gap-x-16">
                    <a href="{% url 'home_app:guarantee' %}"
                       class="flex items-center gap-x-2 md:gap-x-3 md:text-xl hover:text-orange-300 transition-all">
                            <span class="inline-block w-2 md:w-2.5 h-1 bg-current rounded-full">
                            </span>
                        حریم خصوصی
                    </a>
                    <a href="{% url 'home_app:guarantee' %}"
                       class="flex items-center gap-x-2 md:gap-x-3 md:text-xl hover:text-orange-300 transition-all">
                            <span class="inline-block w-2 md:w-2.5 h-1 bg-current rounded-full">
                            </span>
                        عودت کالا
                    </a>
                    <a href="{% url 'home_app:guarantee' %}"
                       class="flex items-center gap-x-2 md:gap-x-3 md:text-xl hover:text-orange-300 transition-all">
                            <span class="inline-block w-2 md:w-2.5 h-1 bg-current rounded-full">
                            </span>
                        شرایط استفاده
                    </a>
                    <a href="{% url 'product_app:order_detail' %}"
                       class="flex items-center gap-x-2 md:gap-x-3 md:text-xl hover:text-orange-300 transition-all">
                            <span class="inline-block w-2 md:w-2.5 h-1 bg-current rounded-full">
                            </span>
                        ثبت سفارش
                    </a>
                    <a href="{% url 'home_app:FAQ' %}"
                       class="flex items-center gap-x-2 md:gap-x-3 md:text-xl hover:text-orange-300 transition-all">
                            <span class="inline-block w-2 md:w-2.5 h-1 bg-current rounded-full">
                            </span>
                        پرسش های متداول
                    </a>
                    <a href="#"
                       class="flex items-center gap-x-2 md:gap-x-3 md:text-xl hover:text-orange-300 transition-all">
                            <span class="inline-block w-2 md:w-2.5 h-1 bg-current rounded-full">
                            </span>
                        فرصت های شغلی
                    </a>
                    <a href="{% url 'home_app:guarantee' %}"
                       class="flex items-center gap-x-2 md:gap-x-3 md:text-xl hover:text-orange-300 transition-all">
                            <span class="inline-block w-2 md:w-2.5 h-1 bg-current rounded-full">
                            </span>
                        ضمانت نامه ها
                    </a>
                    <a href="{% url 'account_app:contact_form_submit' %}"
                       class="flex items-center gap-x-2 md:gap-x-3 md:text-xl hover:text-orange-300 transition-all">
                            <span class="inline-block w-2 md:w-2.5 h-1 bg-current rounded-full">
                            </span>
                        ارتباط با ما
                    </a>
                </div>
            </div>
            <!-- contact-us-footer  -->
            <div class="mt-10 md:mt-[26px]">
                <h4 class="font-DanaDemiBold text-2xl text-white mb-6 md:mb-7">در تماس باشیم</h4>
                <div class="md:text-xl mb-6 md:mb-10">
                        <span class="flex items-center gap-x-2 md:gap-x-3 text-xl mb-4 md:mb-5">
                            <svg class="w-5 md:w-6 h-5 md:h-6 shrink-0">
                                <use href="#map-pin"></use>
                            </svg>
{{ footer_info.address }} 
                        </span>
                    <div class="flex flex-wrap gap-x-5 gap-y-4 font-DanaMedium">
                        <a href="mailto:info@Coffee.com"
                           class="flex items-center gap-x-2 md:gap-x-3 text-xl text-orange-300">
                            <svg class="w-5 md:w-6 h-5 md:h-6">
                                <use href="#envelope"></use>
                            </svg>
                            <span>{{ footer_info.email }}</span>
                        </a>
                        <div class="flex items-center gap-x-2 md:gap-x-3 text-xl">
                            <svg class="w-5 md:w-6 h-5 md:h-6">
                                <use href="#phone"></use>
                            </svg>
                            {% for phone in phone_company %}
                                <span class="ltr-text">{{ phone }}</span>
                                {% if not phone_company.last == phone %}
                                    -
                                {% endif %}
                            {% endfor %}


                        </div>
                    </div>
                </div>
                <!-- button footer  -->
                <div
                        class="flex grid grid-cols-2 gap-x-1.5 md:gap-x-6 font-DanaMedium md:text-xl child:flex child:flex-grow child:justify-center child:items-center child:gap-x-2 ltr-text">

                    {% if footer_info.telegram %}
                    	<a href="{{ footer_info.telegram }}" class="border-orange-200 text-orange-200 rounded-xl h-1/2">
                        {{ footer_info.id_telegram }}
                        <svg class="w-[26px] h-[26px] md:w-[38px] md:h-[38px]">
                            <use href="#telegram"></use>
                        </svg>
                    </a>
                    {% endif %} 
                    {% if footer_info.eitaa %}
                    	<a href="{{ footer_info.eitaa }}" class="border-orange-200 text-orange-200 rounded-xl h-1/2">
                        {{ footer_info.id_eitaa }}
                        <svg class="w-[26px] h-[26px] md:w-[38px] md:h-[38px]">
                            <use href="#eitaa" style=""></use>
                        </svg>
                    </a>
                    {% endif %} 
                {% if footer_info.instagram %}
                    	<a href="{{ footer_info.instagram }}" class="border-orange-200 text-orange-200 rounded-xl h-1/2">
                        {{ footer_info.id_instagram }}
                        <svg class="w-[26px] h-[26px] md:w-[38px] md:h-[38px]">
                            <use href="#instagram"></use>
                        </svg>
                    </a>
                    {% endif %} 
{% if footer_info.twitter %}
	
                    <a href="{{ footer_info.twitter }}" class="border-orange-200 text-orange-200 rounded-xl">
                        
                        {{ footer_info.id_twitter }}
                        <svg class="w-[26px] h-[26px] md:w-[38px] md:h-[38px]">
                            <use href="#x" style=""></use>
                        </svg>
                    </a>
{% endif %} 

                </div>

            </div>


        </div>

        <div class="flex flex-wrap justify-between items-center gap-x-4 font-DanaMedium text-xs/5 md:text-base border-t border-t-white/10 pt-10 md:pt-11 mt-10 md:mt-11">
            <div class="flex items-center gap-x-2.5">
                <div class="flex-center flex-shrink-0 w-[30px] h-[30px] border border-white/10 rounded-full">
                    <div class="flex-center w-5 h-5 border border-white/20 rounded-full">
                        <div class="w-2.5 h-2.5 bg-gradient-to-t from-orange-200 to-orange-300 rounded-full"></div>
                    </div>
                </div>
                <p>تمام حقوق این رابط کابری متعلق به <span class="text-orange-200">KM-Matin</span>می باشد</p>
            </div>
            <span class="ltr-text mt-auto">Copyright © 2023 Golden Coffee. All rights reserved.</span>
        </div>
    </div>
</footer>

templates/includes/home_page/products.html
{% load static %}
{% load humanize %}
<section class="products">
            <div class="container">
                <!-- section head  -->
                <div class="flex justify-between items-end mb-5 md:mb-12 ">
                    <!-- products list  -->
                    <div>
                        <h3 class="section-title  mt-8 md:mt-[120px]">جدیدترین محصولات</h3>
                        <span class="section-subtitle">فرآوری شده از دانه قهوه</span>
                    </div>
                    <a href="{% url 'product_app:product_list' %}" class="section-link">
                        <!-- Desktop Mode  -->
                        
                        <span class="hidden md:inline-block">مشاهده همه محصولات</span>
                        <!-- Mobile Mode  -->
                        <span class="inline-block md:hidden">مشاهده همه</span>
                        <svg class="w-5 h-5">
                            <use href="#chevron-left"></use>
                        </svg>
                    </a>
                </div>
                <!-- section body  -->
                {% include 'includes/extends/show_products.html' %}

            </div>
        </section>

templates/includes/home_page/protractCategory.html
{% load static %}        
<!-- proudacts category  -->
        <section class="proudacts-category mb-10 md:mb-20">
            <div class="container">
                <div class="flex items-center justify-center gap-y-6 gap-x-[29px] md:gap-[65px] flex-wrap">
                    {% for category in categories %}
                    	<div class="w-25 md:w-50 text-center">
                        <div>
                            <img src="{{ category.img.url }}" alt="{{ category.name }}" loading="lazy">
                        </div>
                        <span
                            class="inline-block h-8 font-DanaDemiBold text-sm md:text-xl text-zinc-700 dark:text-white mt-1.5 md:mt-2.5">{{ category.name }}</span>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </section>

templates/includes/home_page/topHeader.html
{% load static %}

        <section
            class="home relative h-[200px] xs:h-auto xs:aspect-[2/1] md:aspect-auto bg-homeMobile md:bg-homeDesktop bg-no-repeat bg-cover bg-[center_top]">

            <div class="container relative h-full md:min-h-screen flex justify-end items-center overflow-y-hidden">
                <!-- informations  -->
                <div class="text-white">
                    <h2 class="font-MorabbaBold text-2xl mb-0.5 md:text-6xl md:mb-2">قهوه عربیکا تانزانیا</h2>
                    <span class="font-MorabbaBold text-xl md:text-5xl">یک فنجان بالانس !</span>
                    <div class="block w-[100px] h-px bg-orange-300 my-3 md:my-8 md:h-0.5"></div>
                    <div class="max-w-[201px] md:max-w-[460px] text-xs md:text-2xl">قطعا نام آشنای عربیکا را شنیده اید،
                        عربیکا یکی از
                        گونه
                        های قهوه است که در نواحی مختلف کمربند قهوه
                        کشت
                        میشود.
                    </div>

                </div>
                <!-- Circle  -->
                <div class="circle circle--lg circle--main">
                    <div class="circle circle--md">
                        <div class="circle circle--sm">
                        </div>
                    </div>
                </div>
            </div>
            <!-- curve  -->

            <svg
                class="absolute bottom-0 right-0 left-0 mx-auto hidden md:inline-block text-gray-100 dark:text-zinc-800 w-[100px] h-[22px]">
                <use href="#curve"></use>
            </svg>

            <!-- Arrow circle  -->
            <div
                class="absolute bottom-0 right-0 left-0 mx-auto translate-y-2/4 hidden md:flex items-center justify-center w-[30px] h-[30px] border-2 border-orange-300 rounded-full">
                <svg class="w-5 h-5 text-zinc-700 dark:text-white">
                    <use href="#chevron-down"></use>
                </svg>
            </div>
        </section>